### ISSUE TITLE
HexagonTests for the adapters fail when they use external dependencies

### ISSUE THREAD

**Issue by L7R7** [sebsprenger/hexagon-enforcement#1]
The following two tests fail as soon as there are external dependencies other than the inner layers of the application:
* [`com.example.app.HexagonTest#primaryAdapterDependecies`](https://github.com/sebsprenger/hexagon-enforcement/blob/master/src/test/java/com/example/app/HexagonTest.java#L37)
* [`com.example.app.HexagonTest#secondaryAdaptersDependencies`](https://github.com/sebsprenger/hexagon-enforcement/blob/master/src/test/java/com/example/app/HexagonTest.java#L49)

I think these tests should be deleted because in a non-trivial project the primary and secondary adapters will always have dependencies to external libraries and frameworks. There are tests to verify that no inner layer (`application` and `domain`) depend on the adapters, so I would say that it's fine to remove the two test cases.

**Comment by sebsprenger** [comment]
I concurr.  `primaryAdaptersDependents()` and `secondaryAdapterDependent()` already ensure that primary and secondary adapters do not refer to each other.
Right now the repo only uses whitelist tests.  Blacklist tests would increase expressiveness.  Maybe I'll add such in the future ;-)

**Comment by sebsprenger** [comment]
Removed in https://github.com/sebsprenger/hexagon-enforcement/commit/44edca6948d5618cd4ff45555c36383cafc97910
